### ISSUE TITLE
0.4.2 failing to parse variable interpolation in mutli line string

### ISSUE THREAD

**Issue by tin-ot** [gruebel/pycep#230]
Hello,

I am currently just trying to look into the project,

It seems that there is issues to parse bicep files with multi line strings 

- version :

 pip freeze | grep pycep
pycep-parser==0.4.2

- snippet

resource name 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {

.....
 

        {
          query: format(
            '''l

- error when parsing :

lark.exceptions.UnexpectedCharacters: No terminal matches ''' in the current parser context, at line 35 col 13

            '''
            
            
           ( I guess the failing character might be any of the character inside to querry for metrics )

**Comment by gruebel** [comment]
hey @tin-ot thanks for reaching out.

Did you try the preview releases? You can find them on [pypi](https://pypi.org/project/pycep-parser/#history). If it works, then great. If not, then please provide a complete example, enough to reproduce it.

**Comment by tin-ot** [comment]
Indeed I started by trying the latest Pypi version
Ans it is failing as well

it is not a specific character more the interpolation in the multiline that is failing to be parsed I will update issue title.

pip freeze | grep pycep
pycep==1.0.4
pycep-parser==0.4.2

Here are steps to reproduce :

created bicep file will a structure of a Microsoft.Insights/scheduledQueryRules

Then :

Multi line query OK

```bicep
resource myalert 'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
......
      allOf: [
        {
          query: '''AzureDiagnostics
          my multiline
          query without any variable
          '''
       .....
 ```
 
 
Multi line query **NOK**

```bicep
resource myalert  'Microsoft.Insights/scheduledQueryRules@2023-03-15-preview' = {
......
      allOf: [
        {
          query: format(
          '''AzureDiagnostics
          my multilin
          query with {0} ''', myvariable
         )

       .....
```

Hope this help !


By the way I don't if it is supposed to be supported but loops like :
cidrSubnet( )
<https://learn.microsoft.com/en-us/azure/azure-resource-manager/bicep/bicep-functions-cidr#cidrsubnet>
is breaking parser as well
